export const doctors = [
  {
    id: 1,
    name: "Dr. Sarah Jenkins",
    email: "sarah.jenkins@clinic.com",
    specialty: "Cardiology",
    secretary: "Mark Thompson",
    status: "Active",
    appointmentsToday: 8,
    phone: "+1 (555) 123-4567",
    avatar: "SJ",
  },
  {
    id: 2,
    name: "Dr. Robert Chen",
    email: "robert.chen@clinic.com",
    specialty: "Pediatrics",
    secretary: "Lisa Wong",
    status: "In Surgery",
    appointmentsToday: 4,
    phone: "+1 (555) 987-6543",
    avatar: "RC",
  },
  {
    id: 3,
    name: "Dr. Emily Davis",
    email: "emily.davis@clinic.com",
    specialty: "Neurology",
    secretary: "David Smith",
    status: "On Leave",
    appointmentsToday: 0,
    phone: "+1 (555) 456-7890",
    avatar: "ED",
  },
  {
    id: 4,
    name: "Dr. Michael Brown",
    email: "michael.brown@clinic.com",
    specialty: "Orthopedics",
    secretary: "Anna Wilson",
    status: "Active",
    appointmentsToday: 11,
    phone: "+1 (555) 222-1111",
    avatar: "MB",
  },
  {
    id: 5,
    name: "Dr. Aisha Khan",
    email: "aisha.khan@clinic.com",
    specialty: "Dermatology",
    secretary: "Omar Hassan",
    status: "Active",
    appointmentsToday: 6,
    phone: "+1 (555) 333-2222",
    avatar: "AK",
  },
  {
    id: 6,
    name: "Dr. James Wilson",
    email: "james.wilson@clinic.com",
    specialty: "General Medicine",
    secretary: "Nora Clark",
    status: "Inactive",
    appointmentsToday: 0,
    phone: "+1 (555) 444-3333",
    avatar: "JW",
  },
  {
    id: 7,
    name: "Dr. Lina Haddad",
    email: "lina.haddad@clinic.com",
    specialty: "Gynecology",
    secretary: "Maya Brooks",
    status: "Active",
    appointmentsToday: 9,
    phone: "+1 (555) 555-4444",
    avatar: "LH",
  },
  {
    id: 8,
    name: "Dr. Daniel Carter",
    email: "daniel.carter@clinic.com",
    specialty: "Psychiatry",
    secretary: "Ethan Reed",
    status: "On Leave",
    appointmentsToday: 0,
    phone: "+1 (555) 666-5555",
    avatar: "DC",
  },
  {
    id: 9,
    name: "Dr. Maria Garcia",
    email: "maria.garcia@clinic.com",
    specialty: "Endocrinology",
    secretary: "Sophia Green",
    status: "Active",
    appointmentsToday: 5,
    phone: "+1 (555) 777-6666",
    avatar: "MG",
  },
  {
    id: 10,
    name: "Dr. Noah Anderson",
    email: "noah.anderson@clinic.com",
    specialty: "Radiology",
    secretary: "Lucas King",
    status: "In Surgery",
    appointmentsToday: 3,
    phone: "+1 (555) 888-7777",
    avatar: "NA",
  },
  {
    id: 11,
    name: "Dr. Fatima Ali",
    email: "fatima.ali@clinic.com",
    specialty: "Ophthalmology",
    secretary: "Hannah Scott",
    status: "Active",
    appointmentsToday: 7,
    phone: "+1 (555) 999-8888",
    avatar: "FA",
  },
  {
    id: 12,
    name: "Dr. Benjamin Lee",
    email: "benjamin.lee@clinic.com",
    specialty: "Urology",
    secretary: "Grace Adams",
    status: "Inactive",
    appointmentsToday: 0,
    phone: "+1 (555) 111-9999",
    avatar: "BL",
  },
];