export const doctors = [
  {
    id: 1,
    created_at: "2026-01-05T08:30:00.000Z",
    updated_at: "2026-06-10T11:15:00.000Z",
    userId: 101,
    specialization: "Cardiology",
    subSpecialization: "Interventional Cardiology",
    licenseNumber: "CARD-20491",
    experienceYears: 12,
    bio: "Focuses on complex heart conditions, preventive cardiology, and long-term treatment planning.",
    initialVisitFee: 140,
    returnVisitFee: 95,
    languagesSpoken: ["English", "Arabic"],
    status: "ACTIVE",
    isApproved: true,
    invitedByAdminId: 1,
    averageRating: 4.8,
    clinics_count: 3,
    user: {
      id: 101,
      created_at: "2026-01-05T08:30:00.000Z",
      updated_at: "2026-06-10T11:15:00.000Z",
      email: "sarah.jenkins@clinic.com",
      provider: "LOCAL",
      providerId: null,
      phone: "+1 (555) 123-4567",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Sarah",
      fatherName: "Anne",
      lastName: "Jenkins",
      birthDate: "1986-04-12",
      gender: "FEMALE",
      address: "24 Lakeview Avenue, Boston, MA",
      avatarUrl: "",
      isVerified: true,
      verificationCode: null,
      verificationCodeExpiresAt: null,
      role: "DOCTOR",
      status: "ACTIVE",
      tokenVersion: 1,
      full_name: "Dr. Sarah Jenkins",
      age: 40,
      age_group: "ADULT",
    },
  },
  {
    id: 2,
    created_at: "2026-01-11T09:45:00.000Z",
    updated_at: "2026-06-03T14:20:00.000Z",
    userId: 102,
    specialization: "Pediatrics",
    subSpecialization: "Pediatric Allergy",
    licenseNumber: "PED-11842",
    experienceYears: 8,
    bio: "Treats childhood respiratory and allergy cases with a strong focus on family education.",
    initialVisitFee: 110,
    returnVisitFee: 75,
    languagesSpoken: ["English", "Mandarin"],
    status: "ACTIVE",
    isApproved: true,
    invitedByAdminId: 1,
    averageRating: 4.6,
    clinics_count: 2,
    user: {
      id: 102,
      created_at: "2026-01-11T09:45:00.000Z",
      updated_at: "2026-06-03T14:20:00.000Z",
      email: "robert.chen@clinic.com",
      provider: "LOCAL",
      providerId: null,
      phone: "+1 (555) 987-6543",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Robert",
      fatherName: "Wei",
      lastName: "Chen",
      birthDate: "1990-09-08",
      gender: "MALE",
      address: "16 Cedar Street, Seattle, WA",
      avatarUrl: "",
      isVerified: true,
      verificationCode: null,
      verificationCodeExpiresAt: null,
      role: "DOCTOR",
      status: "ACTIVE",
      tokenVersion: 1,
      full_name: "Dr. Robert Chen",
      age: 35,
      age_group: "ADULT",
    },
  },
  {
    id: 3,
    created_at: "2026-02-02T07:20:00.000Z",
    updated_at: "2026-05-29T16:40:00.000Z",
    userId: 103,
    specialization: "Neurology",
    subSpecialization: "Stroke Medicine",
    licenseNumber: "NEU-33451",
    experienceYears: 15,
    bio: "Specializes in post-stroke care, diagnostics, and interdisciplinary recovery planning.",
    initialVisitFee: 160,
    returnVisitFee: 120,
    languagesSpoken: ["English", "Spanish"],
    status: "ON_LEAVE",
    isApproved: true,
    invitedByAdminId: 2,
    averageRating: 4.9,
    clinics_count: 1,
    user: {
      id: 103,
      created_at: "2026-02-02T07:20:00.000Z",
      updated_at: "2026-05-29T16:40:00.000Z",
      email: "emily.davis@clinic.com",
      provider: "LOCAL",
      providerId: null,
      phone: "+1 (555) 456-7890",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Emily",
      fatherName: "Rose",
      lastName: "Davis",
      birthDate: "1983-11-19",
      gender: "FEMALE",
      address: "88 Willow Drive, Denver, CO",
      avatarUrl: "",
      isVerified: true,
      verificationCode: null,
      verificationCodeExpiresAt: null,
      role: "DOCTOR",
      status: "ACTIVE",
      tokenVersion: 1,
      full_name: "Dr. Emily Davis",
      age: 42,
      age_group: "ADULT",
    },
  },
  {
    id: 4,
    created_at: "2026-02-14T10:15:00.000Z",
    updated_at: "2026-06-15T09:10:00.000Z",
    userId: 104,
    specialization: "Orthopedics",
    subSpecialization: "Sports Medicine",
    licenseNumber: "ORT-55327",
    experienceYears: 10,
    bio: "Works on joint injuries, sports rehabilitation, and mobility-focused treatment plans.",
    initialVisitFee: 130,
    returnVisitFee: 90,
    languagesSpoken: ["English"],
    status: "ACTIVE",
    isApproved: false,
    invitedByAdminId: 2,
    averageRating: 4.3,
    clinics_count: 2,
    user: {
      id: 104,
      created_at: "2026-02-14T10:15:00.000Z",
      updated_at: "2026-06-15T09:10:00.000Z",
      email: "michael.brown@clinic.com",
      provider: "LOCAL",
      providerId: null,
      phone: "+1 (555) 222-1111",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Michael",
      fatherName: "Adam",
      lastName: "Brown",
      birthDate: "1988-02-27",
      gender: "MALE",
      address: "73 Brookfield Road, Austin, TX",
      avatarUrl: "",
      isVerified: true,
      verificationCode: null,
      verificationCodeExpiresAt: null,
      role: "DOCTOR",
      status: "ACTIVE",
      tokenVersion: 1,
      full_name: "Dr. Michael Brown",
      age: 38,
      age_group: "ADULT",
    },
  },
  {
    id: 5,
    created_at: "2026-03-03T12:05:00.000Z",
    updated_at: "2026-06-12T13:50:00.000Z",
    userId: 105,
    specialization: "Dermatology",
    subSpecialization: "Cosmetic Dermatology",
    licenseNumber: "DERM-90217",
    experienceYears: 9,
    bio: "Handles chronic skin conditions and cosmetic dermatology with patient-centered treatment planning.",
    initialVisitFee: 125,
    returnVisitFee: 85,
    languagesSpoken: ["English", "Urdu", "Arabic"],
    status: "ACTIVE",
    isApproved: true,
    invitedByAdminId: 1,
    averageRating: 4.7,
    clinics_count: 4,
    user: {
      id: 105,
      created_at: "2026-03-03T12:05:00.000Z",
      updated_at: "2026-06-12T13:50:00.000Z",
      email: "aisha.khan@clinic.com",
      provider: "LOCAL",
      providerId: null,
      phone: "+1 (555) 333-2222",
      preferredLanguage: "Arabic",
      themeMode: "light",
      firstName: "Aisha",
      fatherName: "Farah",
      lastName: "Khan",
      birthDate: "1991-07-15",
      gender: "FEMALE",
      address: "39 Riverbend Lane, Chicago, IL",
      avatarUrl: "",
      isVerified: true,
      verificationCode: null,
      verificationCodeExpiresAt: null,
      role: "DOCTOR",
      status: "ACTIVE",
      tokenVersion: 1,
      full_name: "Dr. Aisha Khan",
      age: 34,
      age_group: "ADULT",
    },
  },
  {
    id: 6,
    created_at: "2026-03-18T15:00:00.000Z",
    updated_at: "2026-06-08T08:35:00.000Z",
    userId: 106,
    specialization: "Radiology",
    subSpecialization: "Diagnostic Imaging",
    licenseNumber: "RAD-44108",
    experienceYears: 13,
    bio: "Supports cross-specialty diagnostic work with expertise in imaging reviews and reporting.",
    initialVisitFee: 150,
    returnVisitFee: 105,
    languagesSpoken: ["English", "French"],
    status: "INACTIVE",
    isApproved: true,
    invitedByAdminId: 3,
    averageRating: 4.4,
    clinics_count: 1,
    user: {
      id: 106,
      created_at: "2026-03-18T15:00:00.000Z",
      updated_at: "2026-06-08T08:35:00.000Z",
      email: "noah.anderson@clinic.com",
      provider: "LOCAL",
      providerId: null,
      phone: "+1 (555) 888-7777",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Noah",
      fatherName: "James",
      lastName: "Anderson",
      birthDate: "1985-01-22",
      gender: "MALE",
      address: "140 Pine Crest, Portland, OR",
      avatarUrl: "",
      isVerified: true,
      verificationCode: null,
      verificationCodeExpiresAt: null,
      role: "DOCTOR",
      status: "ACTIVE",
      tokenVersion: 1,
      full_name: "Dr. Noah Anderson",
      age: 41,
      age_group: "ADULT",
    },
  },
];
