export const patients = [
  {
    id: 1,
    created_at: "2026-01-12T08:20:00.000Z",
    updated_at: "2026-06-24T11:10:00.000Z",
    userId: 201,
    maritalStatus: "SINGLE",
    occupation: "Graphic Designer",
    emergencyContactName: "Omar Hassan",
    emergencyContactPhone: "+1 (555) 802-1490",
    noShowCount: 1,
    user: {
      id: 201,
      created_at: "2026-01-12T08:20:00.000Z",
      updated_at: "2026-06-24T11:10:00.000Z",
      email: "layla.hassan@example.com",
      phone: "+1 (555) 201-3478",
      preferredLanguage: "Arabic",
      themeMode: "light",
      firstName: "Layla",
      fatherName: "Samir",
      lastName: "Hassan",
      birthDate: "1997-04-12",
      gender: "FEMALE",
      address: "214 Cedar Avenue, San Francisco, CA",
      avatarUrl: "",
      isVerified: true,
      role: "PATIENT",
      status: "ACTIVE",
      full_name: "Layla Hassan",
      age: 29,
      age_group: "ADULT",
    },
    medicalProfile: {
      id: 3001,
      patientProfileId: 1,
      bloodType: "A+",
      pregnancyStatus: "NOT_PREGNANT",
      disabilityInfo: "None",
      currentSymptoms: "Occasional migraines",
      allergies: "Penicillin",
      chronicConditions: "Migraine",
      pastSurgeries: "Appendectomy in 2018",
      familyHistory: "Hypertension",
      currentMedications: "Ibuprofen as needed",
      lifestyleHabits: "Walks daily, non-smoker",
      vaccinationStatus: "Up to date",
    },
    prescribedMedicines: {
      profileMedicines: [
        {
          id: 5001,
          medicalProfileId: 3001,
          medicalHistoryId: null,
          userId: 201,
          medicineName: "Ibuprofen",
          dosage: "400 mg",
          frequency: "As needed",
          status: "ACTIVE",
          startDate: "2026-05-14",
          endDate: null,
          notes: "Use for migraine episodes. Take with food.",
          created_at: "2026-05-14T10:30:00.000Z",
          updated_at: "2026-06-24T11:10:00.000Z",
        },
        {
          id: 5002,
          medicalProfileId: 3001,
          medicalHistoryId: null,
          userId: 201,
          medicineName: "Magnesium supplement",
          dosage: "250 mg",
          frequency: "Once daily",
          status: "ACTIVE",
          startDate: "2026-06-10",
          endDate: null,
          notes: null,
          created_at: "2026-06-10T09:30:00.000Z",
          updated_at: "2026-06-10T09:30:00.000Z",
        },
      ],
      historyMedicines: [
        {
          id: 5101,
          medicalProfileId: null,
          medicalHistoryId: 4001,
          userId: 201,
          medicineName: "Sumatriptan",
          dosage: "50 mg",
          frequency: "At migraine onset",
          status: "COMPLETED",
          startDate: "2026-06-10",
          endDate: "2026-06-17",
          notes: "Visit-specific migraine treatment.",
          created_at: "2026-06-10T09:20:00.000Z",
          updated_at: "2026-06-17T09:20:00.000Z",
        },
      ],
    },
    medicalHistories: [
      {
        id: 4001,
        medicalProfileId: 3001,
        appointmentId: 1004,
        doctorProfileId: 1,
        diagnosis: "Migraine with episodic flare-ups",
        treatmentPlan:
          "Continue hydration and symptom tracking. Use prescribed rescue medicine only at migraine onset.",
        doctorNotes:
          "Patient reports fewer episodes but still has occasional severe attacks. Reviewed medication safety and follow-up triggers.",
        created_at: "2026-06-18T13:35:00.000Z",
        updated_at: "2026-06-18T13:35:00.000Z",
        appointment: {
          id: 1004,
          requestedDate: "2026-06-18",
          startTime: "13:00:00",
          endTime: "13:30:00",
          status: "completed",
        },
        doctorProfile: {
          id: 1,
          user: {
            firstName: "Sarah",
            lastName: "Jenkins",
            full_name: "Dr. Sarah Jenkins",
          },
        },
      },
    ],
    medicalProfileLogs: [
      {
        id: 6001,
        fieldName: "bloodType",
        oldValue: null,
        newValue: "A+",
        changeReason: "Updated during appointment review",
        appointmentId: 1004,
        createdAt: "2026-06-18T13:35:00.000Z",
        changedBy: {
          id: 1,
          role: "doctor",
          fullName: "Dr. Sarah Jenkins",
        },
      },
      {
        id: 6002,
        fieldName: "allergies",
        oldValue: ["Penicillin"],
        newValue: ["Penicillin", "Peanuts"],
        changeReason: "Updated during appointment review",
        appointmentId: 1004,
        createdAt: "2026-06-18T13:35:00.000Z",
        changedBy: {
          id: 1,
          role: "doctor",
          fullName: "Dr. Sarah Jenkins",
        },
      },
      {
        id: 6003,
        fieldName: "chronicConditions",
        oldValue: null,
        newValue: ["Migraine"],
        changeReason: "Updated during appointment review",
        appointmentId: 1004,
        createdAt: "2026-06-18T13:35:00.000Z",
        changedBy: {
          id: 1,
          role: "doctor",
          fullName: "Dr. Sarah Jenkins",
        },
      },
      {
        id: 6004,
        fieldName: "lifestyleHabits",
        oldValue: "Non-smoker",
        newValue: "Walks daily, non-smoker",
        changeReason: "Admin corrected profile details",
        appointmentId: null,
        createdAt: "2026-06-24T11:10:00.000Z",
        changedBy: {
          id: 900,
          role: "admin",
          fullName: "Admin User",
        },
      },
    ],
    appointments: [
      { id: 9001, status: "COMPLETED", date: "2026-06-10T09:00:00.000Z" },
      { id: 9002, status: "UPCOMING", date: "2026-07-04T13:30:00.000Z" },
    ],
    ratings: [{ id: 7001, score: 5 }, { id: 7002, score: 4 }],
  },
  {
    id: 2,
    created_at: "2026-01-18T10:05:00.000Z",
    updated_at: "2026-06-20T09:45:00.000Z",
    userId: 202,
    maritalStatus: "MARRIED",
    occupation: "Warehouse Supervisor",
    emergencyContactName: "Sarah Murphy",
    emergencyContactPhone: "+1 (555) 483-2051",
    noShowCount: 0,
    user: {
      id: 202,
      created_at: "2026-01-18T10:05:00.000Z",
      updated_at: "2026-06-20T09:45:00.000Z",
      email: "daniel.murphy@example.com",
      phone: "+1 (555) 415-9821",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Daniel",
      fatherName: "Paul",
      lastName: "Murphy",
      birthDate: "1985-09-03",
      gender: "MALE",
      address: "88 Willow Street, Oakland, CA",
      avatarUrl: "",
      isVerified: true,
      role: "PATIENT",
      status: "ACTIVE",
      full_name: "Daniel Murphy",
      age: 41,
      age_group: "ADULT",
    },
    medicalProfile: {
      id: 3002,
      patientProfileId: 2,
      bloodType: "O-",
      pregnancyStatus: "NOT_APPLICABLE",
      disabilityInfo: "Partial hearing loss in left ear",
      currentSymptoms: "Lower back pain",
      allergies: "None",
      chronicConditions: "Type 2 diabetes",
      pastSurgeries: "Knee surgery in 2021",
      familyHistory: "Diabetes",
      currentMedications: "Metformin",
      lifestyleHabits: "Former smoker, light exercise",
      vaccinationStatus: "Up to date",
    },
    prescribedMedicines: {
      profileMedicines: [
        {
          id: 5003,
          medicalProfileId: 3002,
          medicalHistoryId: null,
          userId: 202,
          medicineName: "Metformin",
          dosage: "500 mg",
          frequency: "Twice daily",
          status: "ACTIVE",
          startDate: "2026-02-01",
          endDate: null,
          notes: "Monitor glucose logs at follow-up.",
          created_at: "2026-02-01T08:00:00.000Z",
          updated_at: "2026-06-20T09:45:00.000Z",
        },
      ],
      historyMedicines: [
        {
          id: 5102,
          medicalProfileId: null,
          medicalHistoryId: 4002,
          userId: 202,
          medicineName: "Naproxen",
          dosage: "250 mg",
          frequency: "Twice daily",
          status: "STOPPED",
          startDate: "2026-05-28",
          endDate: "2026-06-04",
          notes: "Stopped after back pain improved.",
          created_at: "2026-05-28T15:30:00.000Z",
          updated_at: "2026-06-04T15:30:00.000Z",
        },
      ],
    },
    medicalHistories: [
      {
        id: 4002,
        medicalProfileId: 3002,
        appointmentId: 1008,
        doctorProfileId: 2,
        diagnosis: "Lower back strain with improving symptoms",
        treatmentPlan:
          "Short course anti-inflammatory treatment, light stretching, and avoid heavy lifting for one week.",
        doctorNotes:
          "Pain has improved since previous complaint. Advised patient to return if numbness or worsening pain develops.",
        created_at: "2026-06-10T10:05:00.000Z",
        updated_at: "2026-06-10T10:05:00.000Z",
        appointment: {
          id: 1008,
          requestedDate: "2026-06-10",
          startTime: "09:30:00",
          endTime: "10:00:00",
          status: "completed",
        },
        doctorProfile: {
          id: 2,
          user: {
            firstName: "Robert",
            lastName: "Chen",
            full_name: "Dr. Robert Chen",
          },
        },
      },
    ],
    medicalProfileLogs: [
      {
        id: 6005,
        fieldName: "currentSymptoms",
        oldValue: "Lower back pain",
        newValue: "Lower back pain improving",
        changeReason: "Patient reported symptom improvement",
        appointmentId: 1008,
        createdAt: "2026-06-10T10:05:00.000Z",
        changedBy: {
          id: 2,
          role: "doctor",
          fullName: "Dr. Robert Chen",
        },
      },
      {
        id: 6006,
        fieldName: "currentMedications",
        oldValue: ["Metformin"],
        newValue: ["Metformin", "Naproxen"],
        changeReason: "Patient reported symptom improvement",
        appointmentId: 1008,
        createdAt: "2026-06-10T10:05:00.000Z",
        changedBy: {
          id: 2,
          role: "doctor",
          fullName: "Dr. Robert Chen",
        },
      },
      {
        id: 6007,
        fieldName: "disabilityInfo",
        oldValue: null,
        newValue: "Partial hearing loss in left ear",
        changeReason: "Patient updated intake profile",
        appointmentId: null,
        createdAt: "2026-01-18T10:05:00.000Z",
        changedBy: {
          id: 202,
          role: "patient",
          fullName: "Daniel Murphy",
        },
      },
    ],
    appointments: [
      { id: 9003, status: "COMPLETED", date: "2026-05-28T15:00:00.000Z" },
    ],
    ratings: [{ id: 7003, score: 4 }],
  },
  {
    id: 3,
    created_at: "2026-02-05T07:50:00.000Z",
    updated_at: "2026-06-22T13:20:00.000Z",
    userId: 203,
    maritalStatus: "MARRIED",
    occupation: "Teacher",
    emergencyContactName: "James Brooks",
    emergencyContactPhone: "+1 (555) 654-2702",
    noShowCount: 2,
    user: {
      id: 203,
      created_at: "2026-02-05T07:50:00.000Z",
      updated_at: "2026-06-22T13:20:00.000Z",
      email: "maya.brooks@example.com",
      phone: "+1 (555) 990-1134",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Maya",
      fatherName: "Nabil",
      lastName: "Brooks",
      birthDate: "1991-01-25",
      gender: "FEMALE",
      address: "541 Pine Road, Berkeley, CA",
      avatarUrl: "",
      isVerified: true,
      role: "PATIENT",
      status: "ACTIVE",
      full_name: "Maya Brooks",
      age: 35,
      age_group: "ADULT",
    },
    medicalProfile: {
      id: 3003,
      patientProfileId: 3,
      bloodType: "B+",
      pregnancyStatus: "PREGNANT",
      disabilityInfo: "None",
      currentSymptoms: "Fatigue",
      allergies: "Seafood",
      chronicConditions: "Anemia",
      pastSurgeries: "None",
      familyHistory: "Asthma",
      currentMedications: "Iron supplements",
      lifestyleHabits: "Balanced diet, low caffeine",
      vaccinationStatus: "Up to date",
    },
    prescribedMedicines: {
      profileMedicines: [
        {
          id: 5004,
          medicalProfileId: 3003,
          medicalHistoryId: null,
          userId: 203,
          medicineName: "Iron supplement",
          dosage: "65 mg",
          frequency: "Once daily",
          status: "ACTIVE",
          startDate: "2026-04-15",
          endDate: null,
          notes: "Take with vitamin C when possible.",
          created_at: "2026-04-15T11:00:00.000Z",
          updated_at: "2026-06-22T13:20:00.000Z",
        },
      ],
      historyMedicines: [],
    },
    medicalHistories: [],
    medicalProfileLogs: [
      {
        id: 6008,
        fieldName: "pregnancyStatus",
        oldValue: "NOT_PREGNANT",
        newValue: "PREGNANT",
        changeReason: "Patient profile updated after intake review",
        appointmentId: null,
        createdAt: "2026-06-22T13:20:00.000Z",
        changedBy: {
          id: 900,
          role: "admin",
          fullName: "Admin User",
        },
      },
      {
        id: 6009,
        fieldName: "currentSymptoms",
        oldValue: null,
        newValue: "Fatigue",
        changeReason: "Patient profile updated after intake review",
        appointmentId: null,
        createdAt: "2026-06-22T13:20:00.000Z",
        changedBy: {
          id: 900,
          role: "admin",
          fullName: "Admin User",
        },
      },
    ],
    appointments: [
      { id: 9004, status: "UPCOMING", date: "2026-07-06T10:30:00.000Z" },
      { id: 9005, status: "COMPLETED", date: "2026-06-02T08:45:00.000Z" },
    ],
    ratings: [{ id: 7004, score: 5 }, { id: 7005, score: 5 }],
  },
  {
    id: 4,
    created_at: "2026-02-19T12:30:00.000Z",
    updated_at: "2026-06-25T08:15:00.000Z",
    userId: 204,
    maritalStatus: "DIVORCED",
    occupation: "Accountant",
    emergencyContactName: "Ella Carter",
    emergencyContactPhone: "+1 (555) 771-6048",
    noShowCount: 0,
    user: {
      id: 204,
      created_at: "2026-02-19T12:30:00.000Z",
      updated_at: "2026-06-25T08:15:00.000Z",
      email: "noah.carter@example.com",
      phone: "+1 (555) 127-6654",
      preferredLanguage: "English",
      themeMode: "dark",
      firstName: "Noah",
      fatherName: "Hadi",
      lastName: "Carter",
      birthDate: "1974-07-18",
      gender: "MALE",
      address: "907 Lake View Drive, San Jose, CA",
      avatarUrl: "",
      isVerified: false,
      role: "PATIENT",
      status: "INACTIVE",
      full_name: "Noah Carter",
      age: 52,
      age_group: "ADULT",
    },
    medicalProfile: {
      id: 3004,
      patientProfileId: 4,
      bloodType: "AB+",
      pregnancyStatus: "NOT_APPLICABLE",
      disabilityInfo: "None",
      currentSymptoms: "High blood pressure follow-up",
      allergies: "None",
      chronicConditions: "Hypertension",
      pastSurgeries: "Gallbladder removal in 2016",
      familyHistory: "Heart disease",
      currentMedications: "Lisinopril",
      lifestyleHabits: "Low-salt diet",
      vaccinationStatus: "Needs booster",
    },
    prescribedMedicines: {
      profileMedicines: [],
      historyMedicines: [],
    },
    medicalHistories: [],
    medicalProfileLogs: [],
    appointments: [],
    ratings: [],
  },
  {
    id: 5,
    created_at: "2026-03-04T09:55:00.000Z",
    updated_at: "2026-06-19T16:40:00.000Z",
    userId: 205,
    maritalStatus: "SINGLE",
    occupation: "University Student",
    emergencyContactName: "Rachel Thompson",
    emergencyContactPhone: "+1 (555) 228-4410",
    noShowCount: 3,
    user: {
      id: 205,
      created_at: "2026-03-04T09:55:00.000Z",
      updated_at: "2026-06-19T16:40:00.000Z",
      email: "ava.thompson@example.com",
      phone: "+1 (555) 338-9042",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Ava",
      fatherName: "Joseph",
      lastName: "Thompson",
      birthDate: "2003-11-09",
      gender: "FEMALE",
      address: "16 Maple Court, Sacramento, CA",
      avatarUrl: "",
      isVerified: true,
      role: "PATIENT",
      status: "ACTIVE",
      full_name: "Ava Thompson",
      age: 23,
      age_group: "ADULT",
    },
    medicalProfile: {
      id: 3005,
      patientProfileId: 5,
      bloodType: "O+",
      pregnancyStatus: "NOT_PREGNANT",
      disabilityInfo: "None",
      currentSymptoms: "Seasonal allergies",
      allergies: "Pollen",
      chronicConditions: "None",
      pastSurgeries: "None",
      familyHistory: "None reported",
      currentMedications: "Antihistamines",
      lifestyleHabits: "Active lifestyle",
      vaccinationStatus: "Up to date",
    },
    prescribedMedicines: {
      profileMedicines: [
        {
          id: 5005,
          medicalProfileId: 3005,
          medicalHistoryId: null,
          userId: 205,
          medicineName: "Antihistamine",
          dosage: null,
          frequency: null,
          status: "ACTIVE",
          startDate: null,
          endDate: null,
          notes: null,
          created_at: "2026-03-04T09:55:00.000Z",
          updated_at: "2026-06-19T16:40:00.000Z",
        },
      ],
      historyMedicines: [],
    },
    medicalHistories: [],
    medicalProfileLogs: [
      {
        id: 6010,
        fieldName: "allergies",
        oldValue: null,
        newValue: ["Pollen"],
        changeReason: "Patient added allergy details",
        appointmentId: null,
        createdAt: "2026-06-19T16:40:00.000Z",
        changedBy: {
          id: 205,
          role: "patient",
          fullName: "Ava Thompson",
        },
      },
    ],
    appointments: [
      { id: 9006, status: "MISSED", date: "2026-06-12T11:00:00.000Z" },
    ],
    ratings: [{ id: 7006, score: 3 }],
  },
];
