export const patients = [
  {
    id: 1,
    created_at: "2026-01-12T08:20:00.000Z",
    updated_at: "2026-06-24T11:10:00.000Z",
    userId: 201,
    maritalStatus: "SINGLE",
    occupation: "Graphic Designer",
    emergencyContactName: "Omar Hassan",
    emergencyContactPhone: "+1 (555) 802-1490",
    noShowCount: 1,
    user: {
      id: 201,
      created_at: "2026-01-12T08:20:00.000Z",
      updated_at: "2026-06-24T11:10:00.000Z",
      email: "layla.hassan@example.com",
      phone: "+1 (555) 201-3478",
      preferredLanguage: "Arabic",
      themeMode: "light",
      firstName: "Layla",
      fatherName: "Samir",
      lastName: "Hassan",
      birthDate: "1997-04-12",
      gender: "FEMALE",
      address: "214 Cedar Avenue, San Francisco, CA",
      avatarUrl: "",
      isVerified: true,
      role: "PATIENT",
      status: "ACTIVE",
      full_name: "Layla Hassan",
      age: 29,
      age_group: "ADULT",
    },
    medicalProfile: {
      bloodType: "A+",
      pregnancyStatus: "NOT_PREGNANT",
      disabilityInfo: "None",
      currentSymptoms: "Occasional migraines",
      allergies: "Penicillin",
      chronicConditions: "Migraine",
      pastSurgeries: "Appendectomy in 2018",
      familyHistory: "Hypertension",
      currentMedications: "Ibuprofen as needed",
      lifestyleHabits: "Walks daily, non-smoker",
      vaccinationStatus: "Up to date",
    },
    appointments: [
      { id: 9001, status: "COMPLETED", date: "2026-06-10T09:00:00.000Z" },
      { id: 9002, status: "UPCOMING", date: "2026-07-04T13:30:00.000Z" },
    ],
    ratings: [{ id: 7001, score: 5 }, { id: 7002, score: 4 }],
  },
  {
    id: 2,
    created_at: "2026-01-18T10:05:00.000Z",
    updated_at: "2026-06-20T09:45:00.000Z",
    userId: 202,
    maritalStatus: "MARRIED",
    occupation: "Warehouse Supervisor",
    emergencyContactName: "Sarah Murphy",
    emergencyContactPhone: "+1 (555) 483-2051",
    noShowCount: 0,
    user: {
      id: 202,
      created_at: "2026-01-18T10:05:00.000Z",
      updated_at: "2026-06-20T09:45:00.000Z",
      email: "daniel.murphy@example.com",
      phone: "+1 (555) 415-9821",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Daniel",
      fatherName: "Paul",
      lastName: "Murphy",
      birthDate: "1985-09-03",
      gender: "MALE",
      address: "88 Willow Street, Oakland, CA",
      avatarUrl: "",
      isVerified: true,
      role: "PATIENT",
      status: "ACTIVE",
      full_name: "Daniel Murphy",
      age: 41,
      age_group: "ADULT",
    },
    medicalProfile: {
      bloodType: "O-",
      pregnancyStatus: "NOT_APPLICABLE",
      disabilityInfo: "Partial hearing loss in left ear",
      currentSymptoms: "Lower back pain",
      allergies: "None",
      chronicConditions: "Type 2 diabetes",
      pastSurgeries: "Knee surgery in 2021",
      familyHistory: "Diabetes",
      currentMedications: "Metformin",
      lifestyleHabits: "Former smoker, light exercise",
      vaccinationStatus: "Up to date",
    },
    appointments: [
      { id: 9003, status: "COMPLETED", date: "2026-05-28T15:00:00.000Z" },
    ],
    ratings: [{ id: 7003, score: 4 }],
  },
  {
    id: 3,
    created_at: "2026-02-05T07:50:00.000Z",
    updated_at: "2026-06-22T13:20:00.000Z",
    userId: 203,
    maritalStatus: "MARRIED",
    occupation: "Teacher",
    emergencyContactName: "James Brooks",
    emergencyContactPhone: "+1 (555) 654-2702",
    noShowCount: 2,
    user: {
      id: 203,
      created_at: "2026-02-05T07:50:00.000Z",
      updated_at: "2026-06-22T13:20:00.000Z",
      email: "maya.brooks@example.com",
      phone: "+1 (555) 990-1134",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Maya",
      fatherName: "Nabil",
      lastName: "Brooks",
      birthDate: "1991-01-25",
      gender: "FEMALE",
      address: "541 Pine Road, Berkeley, CA",
      avatarUrl: "",
      isVerified: true,
      role: "PATIENT",
      status: "ACTIVE",
      full_name: "Maya Brooks",
      age: 35,
      age_group: "ADULT",
    },
    medicalProfile: {
      bloodType: "B+",
      pregnancyStatus: "PREGNANT",
      disabilityInfo: "None",
      currentSymptoms: "Fatigue",
      allergies: "Seafood",
      chronicConditions: "Anemia",
      pastSurgeries: "None",
      familyHistory: "Asthma",
      currentMedications: "Iron supplements",
      lifestyleHabits: "Balanced diet, low caffeine",
      vaccinationStatus: "Up to date",
    },
    appointments: [
      { id: 9004, status: "UPCOMING", date: "2026-07-06T10:30:00.000Z" },
      { id: 9005, status: "COMPLETED", date: "2026-06-02T08:45:00.000Z" },
    ],
    ratings: [{ id: 7004, score: 5 }, { id: 7005, score: 5 }],
  },
  {
    id: 4,
    created_at: "2026-02-19T12:30:00.000Z",
    updated_at: "2026-06-25T08:15:00.000Z",
    userId: 204,
    maritalStatus: "DIVORCED",
    occupation: "Accountant",
    emergencyContactName: "Ella Carter",
    emergencyContactPhone: "+1 (555) 771-6048",
    noShowCount: 0,
    user: {
      id: 204,
      created_at: "2026-02-19T12:30:00.000Z",
      updated_at: "2026-06-25T08:15:00.000Z",
      email: "noah.carter@example.com",
      phone: "+1 (555) 127-6654",
      preferredLanguage: "English",
      themeMode: "dark",
      firstName: "Noah",
      fatherName: "Hadi",
      lastName: "Carter",
      birthDate: "1974-07-18",
      gender: "MALE",
      address: "907 Lake View Drive, San Jose, CA",
      avatarUrl: "",
      isVerified: false,
      role: "PATIENT",
      status: "INACTIVE",
      full_name: "Noah Carter",
      age: 52,
      age_group: "ADULT",
    },
    medicalProfile: {
      bloodType: "AB+",
      pregnancyStatus: "NOT_APPLICABLE",
      disabilityInfo: "None",
      currentSymptoms: "High blood pressure follow-up",
      allergies: "None",
      chronicConditions: "Hypertension",
      pastSurgeries: "Gallbladder removal in 2016",
      familyHistory: "Heart disease",
      currentMedications: "Lisinopril",
      lifestyleHabits: "Low-salt diet",
      vaccinationStatus: "Needs booster",
    },
    appointments: [],
    ratings: [],
  },
  {
    id: 5,
    created_at: "2026-03-04T09:55:00.000Z",
    updated_at: "2026-06-19T16:40:00.000Z",
    userId: 205,
    maritalStatus: "SINGLE",
    occupation: "University Student",
    emergencyContactName: "Rachel Thompson",
    emergencyContactPhone: "+1 (555) 228-4410",
    noShowCount: 3,
    user: {
      id: 205,
      created_at: "2026-03-04T09:55:00.000Z",
      updated_at: "2026-06-19T16:40:00.000Z",
      email: "ava.thompson@example.com",
      phone: "+1 (555) 338-9042",
      preferredLanguage: "English",
      themeMode: "light",
      firstName: "Ava",
      fatherName: "Joseph",
      lastName: "Thompson",
      birthDate: "2003-11-09",
      gender: "FEMALE",
      address: "16 Maple Court, Sacramento, CA",
      avatarUrl: "",
      isVerified: true,
      role: "PATIENT",
      status: "ACTIVE",
      full_name: "Ava Thompson",
      age: 23,
      age_group: "ADULT",
    },
    medicalProfile: {
      bloodType: "O+",
      pregnancyStatus: "NOT_PREGNANT",
      disabilityInfo: "None",
      currentSymptoms: "Seasonal allergies",
      allergies: "Pollen",
      chronicConditions: "None",
      pastSurgeries: "None",
      familyHistory: "None reported",
      currentMedications: "Antihistamines",
      lifestyleHabits: "Active lifestyle",
      vaccinationStatus: "Up to date",
    },
    appointments: [
      { id: 9006, status: "MISSED", date: "2026-06-12T11:00:00.000Z" },
    ],
    ratings: [{ id: 7006, score: 3 }],
  },
];
