export const secretaries = [
  {
    id: 1,
    employeeCode: "SC-1001",
    name: "Maya Brooks",
    email: "maya.brooks@tabibi.com",
    phone: "+1 (555) 310-4401",
    clinic: "Downtown Clinic",
    position: "Front Desk Secretary",
    shift: "Morning",
    status: "Active",
    assignedDoctors: 4,
    avatar: "MB",
    joinedOn: "2023-03-14",
    address: "245 Madison Avenue, New York, NY",
  },
  {
    id: 2,
    employeeCode: "SC-1002",
    name: "Omar Hassan",
    email: "omar.hassan@tabibi.com",
    phone: "+1 (555) 310-4402",
    clinic: "Westside Clinic",
    position: "Administrative Secretary",
    shift: "Evening",
    status: "Active",
    assignedDoctors: 3,
    avatar: "OH",
    joinedOn: "2022-11-09",
    address: "811 Sunset Boulevard, Los Angeles, CA",
  },
  {
    id: 3,
    employeeCode: "SC-1003",
    name: "Nora Clark",
    email: "nora.clark@tabibi.com",
    phone: "+1 (555) 310-4403",
    clinic: "Lakeside Clinic",
    position: "Reception Secretary",
    shift: "Morning",
    status: "Inactive",
    assignedDoctors: 0,
    avatar: "NC",
    joinedOn: "2021-08-22",
    address: "77 North Harbor Drive, Chicago, IL",
  },
  {
    id: 4,
    employeeCode: "SC-1004",
    name: "Lisa Wong",
    email: "lisa.wong@tabibi.com",
    phone: "+1 (555) 310-4404",
    clinic: "Bayview Clinic",
    position: "Clinic Secretary",
    shift: "Evening",
    status: "Active",
    assignedDoctors: 5,
    avatar: "LW",
    joinedOn: "2024-01-17",
    address: "390 Market Street, San Francisco, CA",
  },
  {
    id: 5,
    employeeCode: "SC-1005",
    name: "Grace Adams",
    email: "grace.adams@tabibi.com",
    phone: "+1 (555) 310-4405",
    clinic: "Greenfield Clinic",
    position: "Support Secretary",
    shift: "Morning",
    status: "Active",
    assignedDoctors: 2,
    avatar: "GA",
    joinedOn: "2023-06-05",
    address: "120 Pine Street, Seattle, WA",
  },
  {
    id: 6,
    employeeCode: "SC-1006",
    name: "Hannah Scott",
    email: "hannah.scott@tabibi.com",
    phone: "+1 (555) 310-4406",
    clinic: "Downtown Clinic",
    position: "Appointment Secretary",
    shift: "Evening",
    status: "Inactive",
    assignedDoctors: 1,
    avatar: "HS",
    joinedOn: "2022-05-30",
    address: "245 Madison Avenue, New York, NY",
  },
];
