/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const STORAGE_KEY = "tabibi.doctor.locale";

// Doctor pages still contain some legacy literal copy. Keeping this catalogue at
// the portal boundary lets those screens switch together while new UI can use
// explicit translated labels. Values entered by clinicians are never changed.
const ARABIC_TEXT = {
  "Dashboard": "لوحة التحكم", "Appointments": "المواعيد", "Appointment": "موعد", "Operations": "العمليات", "Queue": "الانتظار", "Patients": "المرضى", "Referrals": "الإحالات", "Schedule": "الدوام", "Leaves & Time-Off": "الإجازات", "Profile": "الملف الشخصي", "Settings": "الإعدادات", "Log out": "تسجيل الخروج",
  "Loading…": "جارٍ التحميل…", "Loading appointments…": "جارٍ تحميل المواعيد…", "Loading operations…": "جارٍ تحميل العمليات…", "Loading your profile…": "جارٍ تحميل ملفك الشخصي…", "Refresh": "تحديث", "Try again": "حاول مجددًا", "Retry": "إعادة المحاولة", "Cancel": "إلغاء", "Save": "حفظ", "Save changes": "حفظ التغييرات", "Back": "رجوع", "Details": "التفاصيل", "Medical file": "الملف الطبي",
  "Today": "اليوم", "Upcoming": "القادمة", "Completed": "مكتمل", "Confirmed": "مؤكد", "Cancelled": "ملغى", "Pending": "قيد الانتظار", "In progress": "قيد التنفيذ", "No-show": "لم يحضر", "Status": "الحالة", "Priority": "الأولوية", "Date": "التاريخ", "Time": "الوقت", "Patient": "المريض", "Clinic": "العيادة", "Type": "النوع", "Notes": "ملاحظات",
  "Check in": "تسجيل الحضور", "Open queue": "فتح قائمة الانتظار", "Call next patient": "استدعاء المريض التالي", "Start consultation": "بدء الاستشارة", "Complete consultation": "إنهاء الاستشارة", "Start": "بدء", "Complete": "إكمال", "Schedule operation": "جدولة عملية", "Awaiting payment": "بانتظار الدفع", "Ready to start": "جاهز للبدء", "No operations scheduled.": "لا توجد عمليات مجدولة.",
  "Your appointments": "مواعيدك", "Your operations": "عملياتك", "No patients are waiting.": "لا يوجد مرضى بانتظارك.", "No appointments match these filters.": "لا توجد مواعيد تطابق عوامل التصفية.", "No patients found.": "لم يتم العثور على مرضى.", "Search patient name or phone...": "ابحث باسم المريض أو رقم الهاتف...", "Reset filters": "إعادة تعيين عوامل التصفية", "All statuses": "كل الحالات", "All dates": "كل التواريخ", "All priorities": "كل الأولويات",
  "Patient medical file": "الملف الطبي للمريض", "Open full medical file": "فتح الملف الطبي الكامل", "Clinical profile": "الملف السريري", "Clinical lists": "القوائم السريرية", "Allergies": "الحساسيات", "Chronic conditions": "الأمراض المزمنة", "Past surgeries": "العمليات السابقة", "Current medications": "الأدوية الحالية", "Family history": "التاريخ العائلي", "Lifestyle habits": "عادات نمط الحياة", "Vaccination status": "حالة اللقاحات", "Blood type": "فصيلة الدم", "Pregnancy status": "حالة الحمل", "Current symptoms": "الأعراض الحالية", "Reason for change": "سبب التعديل",
  "Complete profile": "إكمال الملف الشخصي", "Personal information": "المعلومات الشخصية", "Professional information": "المعلومات المهنية", "Medical specialty": "الاختصاص الطبي", "Sub-specialty": "الاختصاص الفرعي", "Gender": "الجنس", "Birth date": "تاريخ الميلاد", "Experience": "الخبرة", "Languages": "اللغات", "Initial visit": "الزيارة الأولى", "Return visit": "زيارة المتابعة", "Clinic assignment": "تعيين العيادة", "Assigned clinic": "العيادة المعيّنة", "No clinic is assigned yet.": "لم يتم تعيين عيادة بعد.",
  "Professional biography": "السيرة المهنية", "Consultation tariffs": "تعرفات الاستشارات", "Identity & credentials": "الهوية والمؤهلات", "Account & credentials": "الحساب والمؤهلات", "Contact details": "معلومات التواصل", "Account": "الحساب", "Credentials": "المؤهلات", "Pricing": "التسعير", "Overview": "نظرة عامة", "Metadata": "البيانات الوصفية", "Email address": "البريد الإلكتروني", "Phone number": "رقم الهاتف", "License ID": "رقم الترخيص", "Age": "العمر", "Address": "العنوان", "Primary address": "العنوان الأساسي", "Rating": "التقييم", "Clinics": "العيادات", "Active": "نشط", "N/A": "غير متوفر", "No contact address registered.": "لم يتم تسجيل عنوان للتواصل.",
  "Clinical Dashboard": "لوحة التحكم السريرية", "General Rating": "التقييم العام", "Upcoming Appointments": "المواعيد القادمة", "Your next scheduled visits.": "زياراتك المجدولة القادمة.", "More": "المزيد", "No upcoming appointments.": "لا توجد مواعيد قادمة.", "Manage All Appointments": "إدارة جميع المواعيد", "Doctor appointments": "مواعيد الطبيب", "Review your scheduled visits and manage today's check-ins.": "راجع زياراتك المجدولة وأدر تسجيل حضور اليوم.", "Date & time": "التاريخ والوقت", "Visit": "الزيارة", "Normal priority": "أولوية عادية", "High priority": "أولوية عالية",
  "Doctor Schedule": "جدول الطبيب", "Schedule unavailable": "الجدول غير متاح", "Schedule updates": "تحديثات الجدول", "Loading schedule updates…": "جارٍ تحميل تحديثات الجدول…", "No approved or rejected schedule changes yet.": "لا توجد تغييرات مجدولة مقبولة أو مرفوضة بعد.", "Times": "الأوقات", "Shift type": "نوع الدوام", "No additional notes provided.": "لا توجد ملاحظات إضافية.", "Set availability": "تحديد التوفر", "Request change": "طلب تعديل", "Go back": "رجوع",
  "Patients List": "قائمة المرضى", "Patients unavailable": "المرضى غير متاحين", "Medical File": "الملف الطبي", "Patient Medical File": "الملف الطبي للمريض", "Back to patients": "العودة إلى المرضى", "Refresh record": "تحديث السجل", "Allergy alert": "تنبيه حساسية", "Current clinical information": "المعلومات السريرية الحالية", "Additional information": "معلومات إضافية", "Clinical consultation record": "سجل الاستشارة السريرية", "Doctor notes": "ملاحظات الطبيب", "Prescribed medicines": "الأدوية الموصوفة", "No files in this group.": "لا توجد ملفات في هذه المجموعة.", "From:": "من:", "To:": "إلى:",
  "Consultation History": "سجل الاستشارات", "Attachments": "المرفقات", "Profile changes": "تغييرات الملف", "Profile attachments": "مرفقات الملف", "Consultation attachments": "مرفقات الاستشارة", "No attachments": "لا توجد مرفقات", "No profile changes": "لا توجد تغييرات على الملف", "None recorded": "لا توجد معلومات مسجلة", "Live record from appointment": "سجل مباشر من الموعد",
  "Live consultation": "استشارة مباشرة", "Consultation unavailable": "الاستشارة غير متاحة", "Start this consultation from the queue": "ابدأ هذه الاستشارة من قائمة الانتظار", "Visit details": "تفاصيل الزيارة", "Reason for visit": "سبب الزيارة", "Symptoms": "الأعراض", "Medical profile": "الملف الطبي", "Clinical record": "السجل السريري", "Diagnosis": "التشخيص", "Treatment plan": "خطة العلاج", "Clinical notes": "ملاحظات سريرية", "Prescriptions": "الوصفات الطبية", "Create referral": "إنشاء إحالة", "External referral": "إحالة خارجية", "Follow-up with me": "متابعة معي", "Choose a clinic": "اختر عيادة", "Choose a doctor": "اختر طبيبًا", "Reason": "السبب",
  "Today's Patient Queue": "قائمة انتظار مرضى اليوم", "Current patient": "المريض الحالي", "Waiting queue": "قائمة الانتظار", "No patient is currently active": "لا يوجد مريض نشط حاليًا", "Queue unavailable": "قائمة الانتظار غير متاحة", "Loading referrals…": "جارٍ تحميل الإحالات…", "Previous": "السابق", "Next": "التالي",
  "Leaves & Time Off": "الإجازات والوقت المستقطع", "Time off unavailable": "الوقت المستقطع غير متاح", "Your time-off entries": "إدخالات وقتك المستقطع", "Hours": "الساعات", "Actions": "الإجراءات", "Add time off": "إضافة وقت مستقطع", "Exception date": "تاريخ الاستثناء", "Start time": "وقت البدء", "End time": "وقت الانتهاء", "Continue": "متابعة", "Keep entry": "إبقاء الإدخال",
  "Appointment type": "نوع الموعد", "Operation date": "تاريخ العملية", "Operation cost": "تكلفة العملية", "Procedure and preparation notes": "ملاحظات الإجراء والتحضير", "Choose a patient": "اختر مريضًا", "Back to appointments": "العودة إلى المواعيد", "Visit actions": "إجراءات الزيارة", "Appointment notes": "ملاحظات الموعد", "Closed appointment": "موعد مغلق", "Cancel appointment": "إلغاء الموعد", "Cancellation reason": "سبب الإلغاء", "Keep appointment": "إبقاء الموعد", "Mark no-show": "تحديد كعدم حضور",
  "Back to queue": "العودة إلى قائمة الانتظار", "Consultation": "استشارة", "Completing…": "جارٍ الإنهاء…", "Clinical record saved": "تم حفظ السجل السريري", "Saved in this session": "تم الحفظ في هذه الجلسة", "Add medicine": "إضافة دواء", "No medicine prescribed.": "لا توجد أدوية موصوفة.", "Medicine name": "اسم الدواء", "Dosage": "الجرعة", "Frequency": "التكرار", "Instructions": "التعليمات", "Remove medicine": "إزالة الدواء", "Save clinical record": "حفظ السجل السريري", "Starting…": "جارٍ البدء…", "Skip": "تخطي", "Resume consultation": "استئناف الاستشارة",
  "Sunday": "الأحد", "Monday": "الاثنين", "Tuesday": "الثلاثاء", "Wednesday": "الأربعاء", "Thursday": "الخميس", "Friday": "الجمعة", "Saturday": "السبت", "NORMAL": "عادي", "BREAK": "استراحة", "EMERGENCY": "طارئ", "OPERATION": "عمليات",
  "Profile incomplete": "الملف الشخصي غير مكتمل", "Edit profile": "تعديل الملف الشخصي", "Fill in your personal and professional information.": "أدخل معلوماتك الشخصية والمهنية.", "Select gender": "اختر الجنس", "Male": "ذكر", "Female": "أنثى", "Profile completion": "اكتمال الملف الشخصي", "All required profile details are complete.": "اكتملت جميع تفاصيل الملف المطلوبة.", "Clinic assignment required": "تعيين العيادة مطلوب", "Check again": "تحقق مجددًا", "Loading specialties…": "جارٍ تحميل الاختصاصات…", "Select medical specialty": "اختر الاختصاص الطبي", "Select sub-specialty": "اختر الاختصاص الفرعي", "Select a specialty first": "اختر اختصاصًا طبيًا أولًا", "Syndicate license number": "رقم ترخيص النقابة", "Experience years (optional)": "سنوات الخبرة (اختياري)", "Initial visit fee": "تعرفة الزيارة الأولى", "Return visit fee": "تعرفة زيارة المتابعة", "Languages spoken": "اللغات المتحدث بها",
  "No values recorded.": "لا توجد قيم مسجلة.", "Not recorded": "غير مسجل", "Pregnant": "حامل", "Not pregnant": "غير حامل", "Unknown": "غير معروف", "Choose a common value": "اختر قيمة شائعة", "No lookup values available": "لا توجد قيم مرجعية متاحة", "Add custom value": "إضافة قيمة مخصصة", "Choose a common disability type": "اختر نوع إعاقة شائع", "Disability information": "معلومات الإعاقة", "Required credentials and optional practice details.": "المؤهلات المطلوبة وتفاصيل الممارسة الاختيارية.",
  "These are active schedule exceptions.": "هذه استثناءات فعّالة في الجدول.", "Total": "الإجمالي", "Partial hours": "ساعات جزئية", "Full day": "يوم كامل", "Whole day": "اليوم كامل", "No reason provided": "لم يُذكر سبب", "Remove time off": "إزالة الوقت المستقطع", "No time-off entries yet.": "لا توجد إدخالات وقت مستقطع بعد.",
  "TABIBI PORTAL": "بوابة طبيبي", "Request Change": "طلب تعديل", "Set Availability": "تحديد التوفر", "Refresh schedule": "تحديث الجدول", "Active Slots": "فترات نشطة", "No shifts scheduled for": "لا توجد فترات دوام مجدولة ليوم", "Set your availability for this day, or wait for an approved schedule-change request.": "حدّد توفرك لهذا اليوم أو انتظر الموافقة على طلب تعديل الجدول.", "Approval and rejection information from the clinic.": "معلومات القبول والرفض الواردة من العيادة.", "Refresh updates": "تحديث التحديثات", "Schedule change rejected": "تم رفض تعديل الجدول", "Schedule change approved": "تمت الموافقة على تعديل الجدول", "Your schedule update was reviewed.": "تمت مراجعة تحديث جدولك.", "Submit this schedule change for approval?": "إرسال تعديل الجدول للموافقة؟", "Set this initial availability immediately?": "تعيين التوفر الأولي فورًا؟", "Submit request": "إرسال الطلب", "Request Schedule Change": "طلب تعديل الجدول", "Close schedule form": "إغلاق نموذج الجدول", "Your current schedule stays active until an administrator reviews this change request.": "يبقى جدولك الحالي نشطًا حتى يراجع المسؤول طلب التعديل.", "Your first availability for this day will be saved immediately.": "سيتم حفظ أول توفر لك لهذا اليوم فورًا.", "Optional notes": "ملاحظات اختيارية", "Add another slot": "إضافة فترة أخرى", "Save availability": "حفظ التوفر",
  "Sent referrals": "الإحالات المرسلة", "Received referrals": "الإحالات المستلمة", "Referrals you created from patient consultations.": "الإحالات التي أنشأتها من استشارات المرضى.", "Active referrals specifically addressed to you.": "الإحالات الفعّالة الموجّهة إليك تحديدًا.", "Sent": "المرسلة", "Received": "المستلمة", "Search this page of": "ابحث في هذه الصفحة من", "No sent referrals found.": "لم يتم العثور على إحالات مرسلة.", "No received referrals found.": "لم يتم العثور على إحالات مستلمة.", "Create referrals from an active consultation.": "أنشئ الإحالات من استشارة نشطة.", "The backend currently returns pending referrals addressed to you.": "يعرض النظام حاليًا الإحالات المعلقة الموجّهة إليك.", "Page": "الصفحة", "of": "من", "referrals": "إحالات", "Follow-up": "متابعة", "External": "خارجي", "Created": "أُنشئت", "Expires": "تنتهي", "Referral type": "نوع الإحالة", "Target clinic": "العيادة المستهدفة", "Target doctor": "الطبيب المستهدف", "Clinical reason for this referral": "السبب السريري لهذه الإحالة", "Creating…": "جارٍ الإنشاء…",
  "Patients from your appointments and their available medical records": "مرضى مواعيدك وسجلاتهم الطبية المتاحة", "Search patient...": "ابحث عن مريض...", "No matching patients found.": "لم يتم العثور على مرضى مطابقين.", "You do not have any appointments yet.": "ليس لديك أي مواعيد بعد.", "Last visit:": "آخر زيارة:", "Gender not recorded": "الجنس غير مسجل", "Born": "تاريخ الميلاد", "years": "سنة", "Medical Profile": "الملف الطبي", "Back to consultation": "العودة إلى الاستشارة", "Edit clinical profile": "تعديل الملف السريري", "No allergies recorded": "لا توجد حساسيات مسجلة", "None": "لا يوجد", "None reported": "لا يوجد ما تم الإبلاغ عنه", "Lifestyle": "نمط الحياة", "Vaccinations": "اللقاحات", "No consultation history": "لا يوجد سجل للاستشارات", "Completed consultation records will appear here.": "ستظهر هنا سجلات الاستشارات المكتملة.", "related attachment": "مرفق مرتبط", "related attachments": "مرفقات مرتبطة", "Attachment": "مرفق", "File": "ملف", "Download": "تنزيل", "Downloading…": "جارٍ التنزيل…", "Profile and consultation files will appear here.": "ستظهر هنا ملفات الملف الطبي والاستشارات.", "Medical profile updates will be listed here.": "ستظهر هنا تحديثات الملف الطبي والاستشارات.",
  "Use the managed lookup lists for common values, or add a medically necessary custom value.": "استخدم القوائم المرجعية المُدارة للقيم الشائعة، أو أضف قيمة مخصصة عند الضرورة الطبية.", "Select common values or add custom clinical information.": "اختر قيمًا شائعة أو أضف معلومات سريرية مخصصة.", "Known allergies and sensitivities": "الحساسيات المعروفة وحالات التحسس", "Ongoing diagnoses": "التشخيصات المستمرة", "Relevant surgical history": "التاريخ الجراحي ذي الصلة", "Relevant habits and exposures": "العادات والتعرضات ذات الصلة", "Add clinically relevant family history": "أضف تاريخًا عائليًا ذا صلة سريرية", "Patient-reported ongoing medicines": "الأدوية المستمرة التي أبلغ عنها المريض", "Add relevant vaccination information": "أضف معلومات اللقاحات ذات الصلة", "Written clinical summary": "ملخص سريري مكتوب", "Choose a common type below or add relevant detail": "اختر نوعًا شائعًا أدناه أو أضف تفاصيل ذات صلة", "Or write a specific disability detail": "أو اكتب تفاصيل محددة عن الإعاقة", "This is recorded in the profile-change history.": "يتم تسجيل ذلك في سجل تغييرات الملف.", "For example: Updated after reviewing the patient during today’s consultation.": "مثال: تم التحديث بعد مراجعة المريض خلال استشارة اليوم.", "The clinical record could not be loaded.": "تعذر تحميل السجل السريري.", "The server permits these records only through a doctor-owned, non-cancelled appointment and currently applies a seven-day access window.": "يسمح الخادم بهذه السجلات فقط عبر موعد يخص الطبيب وغير ملغى، ويطبق حاليًا مدة وصول قدرها سبعة أيام.",
  "The backend does not return a patient while they are being called yet. This temporary browser-session entry lets you start or skip them; do not clear browser session data before finishing this handoff.": "لا يعيد الخادم بيانات المريض أثناء استدعائه حاليًا. يسمح هذا الإدخال المؤقت في جلسة المتصفح ببدء الاستشارة أو تخطي المريض؛ لا تمسح بيانات الجلسة قبل إكمال هذه الخطوة.", "Check in a confirmed appointment from its details page.": "سجّل حضور موعد مؤكد من صفحة تفاصيله.", "Calling…": "جارٍ الاستدعاء…", "Patient already active": "هناك مريض نشط بالفعل", "No patients waiting": "لا يوجد مرضى بانتظارك", "estimated wait": "الانتظار المتوقع", "min": "دقيقة", "Open medical file": "فتح الملف الطبي", "Skip patient": "تخطي المريض", "Consultation started.": "بدأت الاستشارة.", "Patient skipped.": "تم تخطي المريض.", "Saved to the patient’s medical history before this consultation is completed.": "يُحفظ في السجل الطبي للمريض قبل إنهاء هذه الاستشارة.", "This creates a live referral for the patient. The backend does not yet link it to this appointment.": "ينشئ هذا إحالة مباشرة للمريض. لا يربط الخادم الإحالة بهذا الموعد حتى الآن.", "This follow-up stays with you, so no clinic or doctor needs to be selected.": "تبقى هذه المتابعة معك، لذلك لا حاجة لاختيار عيادة أو طبيب.", "Choose file": "اختيار ملف",
  "Live queue": "قائمة انتظار مباشرة", "Waiting": "بانتظار", "In consultation": "قيد الاستشارة", "Active queue": "قائمة الانتظار النشطة", "Your assigned clinic:": "عيادتك المعيّنة:", "Clinic not available": "العيادة غير متاحة",
  "Back to medical file": "العودة إلى الملف الطبي", "Update current clinical information for": "تحديث المعلومات السريرية الحالية لـ", "from appointment": "من الموعد",
  "Your schedule change request was rejected.": "تم رفض طلب تعديل جدولك.", "Your schedule change request was approved.": "تمت الموافقة على طلب تعديل جدولك.",
  "Review your weekly operational hours at your assigned clinic.": "راجع ساعات دوامك الأسبوعية في العيادة المعيّنة.", "Review your scheduled visits and manage today’s check-ins.": "راجع مواعيدك المجدولة وأدر تسجيل حضور اليوم.", "Only checked-in appointments appear here.": "تظهر هنا المواعيد التي تم تسجيل حضورها فقط.", "Schedule and manage your paid procedure appointments. Operations do not enter the patient queue.": "جدول وأدر مواعيد العمليات المدفوعة. العمليات لا تدخل قائمة انتظار المرضى.", "A full-day leave blocks the whole day; partial time off blocks only the specified hours.": "الإجازة ليوم كامل تحجب اليوم كله، والوقت المستقطع الجزئي يحجب الساعات المحددة فقط.", "No professional biography registered in the system database.": "لا توجد سيرة مهنية مسجلة في قاعدة بيانات النظام.", "Complete the required personal and professional details": "أكمل التفاصيل الشخصية والمهنية المطلوبة",
};

function localizeTextNodes(root, locale) {
  const translations = locale === "ar" ? ARABIC_TEXT : Object.fromEntries(Object.entries(ARABIC_TEXT).map(([english, arabic]) => [arabic, english]));
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach((node) => {
    const original = node.nodeValue || "";
    const trimmed = original.trim();
    const replacement = translations[trimmed];
    if (!replacement) return;
    node.nodeValue = original.replace(trimmed, replacement);
  });
}

const DoctorLocaleContext = createContext(null);

export function getLookupDisplayName(lookup, locale = "en") {
  if (!lookup) return "";
  if (locale === "ar") return lookup.labelAr || lookup.label_ar || lookup.labelEn || lookup.label_en || lookup.value || "";
  return lookup.labelEn || lookup.label_en || lookup.labelAr || lookup.label_ar || lookup.value || "";
}

export function DoctorLocaleProvider({ children }) {
  const [locale, setLocaleState] = useState(() => window.localStorage.getItem(STORAGE_KEY) === "ar" ? "ar" : "en");

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, locale);
    const previousLanguage = document.documentElement.lang;
    const previousDirection = document.documentElement.dir;
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
    return () => {
      document.documentElement.lang = previousLanguage || "en";
      document.documentElement.dir = previousDirection || "ltr";
    };
  }, [locale]);

  useEffect(() => {
    const root = document.querySelector(".doctor-portal");
    if (!root) return undefined;
    localizeTextNodes(root, locale);
    const observer = new MutationObserver(() => localizeTextNodes(root, locale));
    observer.observe(root, { childList: true, subtree: true, characterData: true });
    return () => observer.disconnect();
  }, [locale]);

  const value = useMemo(() => ({
    locale,
    direction: locale === "ar" ? "rtl" : "ltr",
    setLocale: (nextLocale) => setLocaleState(nextLocale === "ar" ? "ar" : "en"),
    lookupName: (lookup) => getLookupDisplayName(lookup, locale),
    text: (english) => locale === "ar" ? ARABIC_TEXT[english] || english : english,
  }), [locale]);

  return <DoctorLocaleContext.Provider value={value}>{children}</DoctorLocaleContext.Provider>;
}

export function useDoctorLocale() {
  const context = useContext(DoctorLocaleContext);
  if (!context) throw new Error("useDoctorLocale must be used inside DoctorLocaleProvider.");
  return context;
}
