const now = new Date();
const today = now.toISOString().slice(0, 10);

function minutesAgo(minutes) {
  return new Date(now.getTime() - minutes * 60000).toISOString();
}

function appointment({
  id,
  patientId,
  doctorId,
  clinicId,
  patientName,
  startTime,
  endTime,
  type,
  priority = "1",
}) {
  const [firstName, fatherName, lastName] = patientName.split(" ");

  return {
    id,
    patientId,
    doctorId,
    clinicId,
    type,
    priority,
    status: "confirmed",
    requestedDate: today,
    startTime,
    endTime,
    patient: {
      id: patientId,
      user: {
        id: patientId + 1000,
        firstName,
        fatherName: lastName ? fatherName : null,
        lastName: lastName || fatherName || "",
        full_name: patientName,
      },
    },
  };
}

export const mockQueueClinics = [
  {
    id: 1,
    name: "Main Clinic",
    description: "General outpatient clinic",
    location: "First floor",
    status: "active",
  },
  {
    id: 2,
    name: "Cardiology",
    description: "Heart care clinic",
    location: "Second floor",
    status: "active",
  },
];

export const mockQueueDoctors = [
  {
    id: 1,
    userId: 201,
    specialization: "General Medicine",
    status: "active",
    isApproved: true,
    clinicIds: [1],
    user: {
      id: 201,
      firstName: "Sara",
      fatherName: null,
      lastName: "Nasser",
      full_name: "Sara Nasser",
    },
  },
  {
    id: 2,
    userId: 202,
    specialization: "Cardiology",
    status: "active",
    isApproved: true,
    clinicIds: [2],
    user: {
      id: 202,
      firstName: "Omar",
      fatherName: null,
      lastName: "Khaled",
      full_name: "Omar Khaled",
    },
  },
  {
    id: 3,
    userId: 203,
    specialization: "Internal Medicine",
    status: "active",
    isApproved: true,
    clinicIds: [1, 2],
    user: {
      id: 203,
      firstName: "Lina",
      fatherName: null,
      lastName: "Haddad",
      full_name: "Lina Haddad",
    },
  },
];

export const mockQueueItems = [
  {
    id: 1,
    appointmentId: 101,
    clinicId: 1,
    doctorId: 1,
    position: 1,
    status: "completed",
    estimatedWaitMinutes: 0,
    checkinTime: minutesAgo(95),
    startedTime: minutesAgo(80),
    finishedTime: minutesAgo(60),
    isPriority: false,
    actualDurationMinutes: 20,
    created_at: minutesAgo(100),
    updated_at: minutesAgo(60),
    appointment: appointment({
      id: 101,
      patientId: 301,
      doctorId: 1,
      clinicId: 1,
      patientName: "Ahmad Samir Ali",
      startTime: "09:00",
      endTime: "09:15",
      type: "consultation",
    }),
    clinic: mockQueueClinics[0],
  },
  {
    id: 2,
    appointmentId: 102,
    clinicId: 1,
    doctorId: 1,
    position: 2,
    status: "in_progress",
    estimatedWaitMinutes: 0,
    checkinTime: minutesAgo(55),
    startedTime: minutesAgo(20),
    finishedTime: null,
    isPriority: true,
    actualDurationMinutes: null,
    created_at: minutesAgo(60),
    updated_at: minutesAgo(20),
    appointment: appointment({
      id: 102,
      patientId: 302,
      doctorId: 1,
      clinicId: 1,
      patientName: "Maya Fadi Hassan",
      startTime: "09:20",
      endTime: "09:35",
      type: "follow_up",
      priority: "2",
    }),
    clinic: mockQueueClinics[0],
  },
  {
    id: 3,
    appointmentId: 103,
    clinicId: 1,
    doctorId: 1,
    position: 3,
    status: "calling",
    estimatedWaitMinutes: 5,
    checkinTime: minutesAgo(45),
    startedTime: null,
    finishedTime: null,
    isPriority: false,
    actualDurationMinutes: null,
    created_at: minutesAgo(48),
    updated_at: minutesAgo(5),
    appointment: appointment({
      id: 103,
      patientId: 303,
      doctorId: 1,
      clinicId: 1,
      patientName: "Nour Basel Amin",
      startTime: "09:40",
      endTime: "09:55",
      type: "consultation",
    }),
    clinic: mockQueueClinics[0],
  },
  {
    id: 4,
    appointmentId: 104,
    clinicId: 1,
    doctorId: 1,
    position: 4,
    status: "waiting",
    estimatedWaitMinutes: 15,
    checkinTime: minutesAgo(30),
    startedTime: null,
    finishedTime: null,
    isPriority: false,
    actualDurationMinutes: null,
    created_at: minutesAgo(32),
    updated_at: minutesAgo(32),
    appointment: appointment({
      id: 104,
      patientId: 304,
      doctorId: 1,
      clinicId: 1,
      patientName: "Karim Tarek Saleh",
      startTime: "10:00",
      endTime: "10:15",
      type: "consultation",
    }),
    clinic: mockQueueClinics[0],
  },
  {
    id: 5,
    appointmentId: 105,
    clinicId: 1,
    doctorId: 1,
    position: 6,
    status: "waiting",
    estimatedWaitMinutes: 30,
    checkinTime: minutesAgo(12),
    startedTime: null,
    finishedTime: null,
    isPriority: true,
    actualDurationMinutes: null,
    created_at: minutesAgo(14),
    updated_at: minutesAgo(14),
    appointment: appointment({
      id: 105,
      patientId: 305,
      doctorId: 1,
      clinicId: 1,
      patientName: "Rana Adel Mansour",
      startTime: "10:20",
      endTime: "10:35",
      type: "operation",
      priority: "2",
    }),
    clinic: mockQueueClinics[0],
  },
  {
    id: 6,
    appointmentId: 106,
    clinicId: 1,
    doctorId: 1,
    position: 5,
    status: "skipped",
    estimatedWaitMinutes: 0,
    checkinTime: minutesAgo(25),
    startedTime: null,
    finishedTime: null,
    isPriority: false,
    actualDurationMinutes: null,
    created_at: minutesAgo(28),
    updated_at: minutesAgo(8),
    appointment: appointment({
      id: 106,
      patientId: 306,
      doctorId: 1,
      clinicId: 1,
      patientName: "Yousef Nabil Darwish",
      startTime: "10:10",
      endTime: "10:25",
      type: "consultation",
    }),
    clinic: mockQueueClinics[0],
  },
  {
    id: 7,
    appointmentId: 107,
    clinicId: 2,
    doctorId: 2,
    position: 1,
    status: "waiting",
    estimatedWaitMinutes: 0,
    checkinTime: minutesAgo(10),
    startedTime: null,
    finishedTime: null,
    isPriority: false,
    actualDurationMinutes: null,
    created_at: minutesAgo(12),
    updated_at: minutesAgo(12),
    appointment: appointment({
      id: 107,
      patientId: 307,
      doctorId: 2,
      clinicId: 2,
      patientName: "Hala Majed Omar",
      startTime: "11:00",
      endTime: "11:15",
      type: "consultation",
    }),
    clinic: mockQueueClinics[1],
  },
];
