export const mockDoctorWeeklyScheduleSlots = [
  {
    id: 1,
    dayOfWeek: 0,
    startTime: "09:00:00",
    endTime: "12:00:00",
    type: "NORMAL",
    clinicId: 1,
    clinicName: "Downtown Clinic",
    notes: "General consultations",
    isActive: true,
  },
  {
    id: 2,
    dayOfWeek: 0,
    startTime: "12:00:00",
    endTime: "12:30:00",
    type: "BREAK",
    clinicId: 1,
    clinicName: "Downtown Clinic",
    notes: "Lunch break",
    isActive: true,
  },
  {
    id: 3,
    dayOfWeek: 0,
    startTime: "13:00:00",
    endTime: "15:00:00",
    type: "NORMAL",
    clinicId: 1,
    clinicName: "Downtown Clinic",
    notes: null,
    isActive: true,
  },
  {
    id: 4,
    dayOfWeek: 1,
    startTime: "10:00",
    endTime: "14:00",
    type: "NORMAL",
    clinicId: 2,
    clinic: {
      id: 2,
      name: "Westside Clinic",
    },
    notes: "Uses backend-style nested clinic data",
    isActive: true,
  },
  {
    id: 5,
    dayOfWeek: 2,
    startTime: "08:30:00",
    endTime: "11:30:00",
    type: "EMERGENCY",
    clinicId: 4,
    clinicName: "Bayview Clinic",
    notes: "Reserved for urgent walk-ins",
    isActive: true,
  },
  {
    id: 6,
    dayOfWeek: 2,
    startTime: "12:00:00",
    endTime: "16:00:00",
    type: "NORMAL",
    clinicId: 4,
    clinicName: "Bayview Clinic",
    notes: "",
    isActive: true,
  },
  {
    id: 7,
    dayOfWeek: 4,
    startTime: "09:30",
    endTime: "13:30",
    type: "NORMAL",
    clinicId: 5,
    clinicName: "Greenfield Clinic",
    notes: "Follow-up appointments",
    isActive: true,
  },
  {
    id: 8,
    dayOfWeek: 4,
    startTime: "14:00:00",
    endTime: "15:00:00",
    type: "BREAK",
    clinicId: 5,
    clinicName: "Greenfield Clinic",
    notes: null,
    isActive: true,
  },
  {
    id: 9,
    dayOfWeek: 5,
    startTime: "16:00:00",
    endTime: "18:00:00",
    type: "NORMAL",
    clinicId: 1,
    clinicName: "Downtown Clinic",
    notes: "Inactive slot hidden by default",
    isActive: false,
  },
  {
    id: 10,
    dayOfWeek: 6,
    startTime: "11:00:00",
    endTime: "13:00:00",
    type: "NORMAL",
    clinicId: 2,
    clinicName: "Westside Clinic",
    notes: "Saturday shift",
    isActive: true,
  },
  {
    id: 11,
    dayOfWeek: 9,
    startTime: "09:00:00",
    endTime: "10:00:00",
    type: "NORMAL",
    clinicId: 1,
    clinicName: "Downtown Clinic",
    notes: "Ignored because dayOfWeek is outside 0-6",
    isActive: true,
  },
];

export const mockEmptyDoctorWeeklyScheduleSlots = [];
