export const mockAppointments = [
  {
    id: 1001,
    patientId: 1,
    doctorId: 1,
    clinicId: 1,
    referralId: null,
    type: "Initial Visit",
    priority: "1",
    status: "confirmed",
    requestedDate: "2026-07-04",
    startTime: "09:00:00",
    endTime: "09:30:00",
    actualStartTime: null,
    actualEndTime: null,
    reasonForVisit: "Chest discomfort during exercise.",
    symptoms: "Shortness of breath and mild pressure.",
    cancellationReason: null,
    cancelledAt: null,
    checkinTime: null,
    notes: "Bring previous ECG results.",
    patient: {
      id: 1,
      user: {
        full_name: "Layla Hassan",
        email: "layla.hassan@example.com",
        phone: "+1 (555) 201-3478",
      },
    },
    doctor: {
      id: 1,
      user: {
        full_name: "Dr. Sarah Jenkins",
        email: "sarah.jenkins@clinic.com",
      },
    },
    clinic: {
      id: 1,
      name: "Downtown Clinic",
      location: "New York",
    },
    payment: {
      status: "held",
      amount: 140,
      paymentMethod: "wallet",
    },
    queue: null,
    referral: null,
    rating: null,
  },
  {
    id: 1002,
    patientId: 2,
    doctorId: 1,
    clinicId: 1,
    referralId: null,
    type: "Return Visit",
    priority: "2",
    status: "confirmed",
    requestedDate: "2026-07-01",
    startTime: "11:00:00",
    endTime: "11:30:00",
    actualStartTime: null,
    actualEndTime: null,
    reasonForVisit: "Blood pressure follow-up.",
    symptoms: "Lightheadedness in the morning.",
    cancellationReason: null,
    cancelledAt: null,
    checkinTime: "2026-07-01T10:48:00.000Z",
    notes: null,
    patient: {
      id: 2,
      user: {
        full_name: "Daniel Murphy",
        email: "daniel.murphy@example.com",
        phone: "+1 (555) 415-9821",
      },
    },
    doctor: {
      id: 1,
      user: {
        full_name: "Dr. Sarah Jenkins",
        email: "sarah.jenkins@clinic.com",
      },
    },
    clinic: {
      id: 1,
      name: "Downtown Clinic",
      location: "New York",
    },
    payment: {
      status: "held",
      amount: 95,
      paymentMethod: "wallet",
    },
    queue: {
      id: 501,
      queueNumber: 4,
      status: "waiting",
    },
    referral: null,
    rating: null,
  },
  {
    id: 1003,
    patientId: 3,
    doctorId: 2,
    clinicId: 2,
    referralId: null,
    type: "Initial Visit",
    priority: "1",
    status: "pending",
    requestedDate: "2026-07-08",
    startTime: "10:00:00",
    endTime: "10:30:00",
    actualStartTime: null,
    actualEndTime: null,
    reasonForVisit: "Child allergy consultation.",
    symptoms: "Seasonal sneezing and rash.",
    cancellationReason: null,
    cancelledAt: null,
    checkinTime: null,
    notes: null,
    patient: {
      id: 3,
      user: {
        full_name: "Maya Brooks",
        email: "maya.brooks@example.com",
        phone: "+1 (555) 990-1134",
      },
    },
    doctor: {
      id: 2,
      user: {
        full_name: "Dr. Robert Chen",
        email: "robert.chen@clinic.com",
      },
    },
    clinic: {
      id: 2,
      name: "Westside Clinic",
      location: "Los Angeles",
    },
    payment: null,
    queue: null,
    referral: null,
    rating: null,
  },
  {
    id: 1004,
    patientId: 1,
    doctorId: 1,
    clinicId: 4,
    referralId: 3001,
    type: "Return Visit",
    priority: "1",
    status: "completed",
    requestedDate: "2026-06-18",
    startTime: "13:00:00",
    endTime: "13:30:00",
    actualStartTime: "2026-06-18T13:04:00.000Z",
    actualEndTime: "2026-06-18T13:31:00.000Z",
    reasonForVisit: "Review cardiac medication response.",
    symptoms: "Improved chest symptoms.",
    cancellationReason: null,
    cancelledAt: null,
    checkinTime: "2026-06-18T12:43:00.000Z",
    notes: "Medication plan adjusted and recorded in medical history.",
    patient: {
      id: 1,
      user: {
        full_name: "Layla Hassan",
        email: "layla.hassan@example.com",
        phone: "+1 (555) 201-3478",
      },
    },
    doctor: {
      id: 1,
      user: {
        full_name: "Dr. Sarah Jenkins",
        email: "sarah.jenkins@clinic.com",
      },
    },
    clinic: {
      id: 4,
      name: "Bayview Clinic",
      location: "San Francisco",
    },
    payment: {
      status: "released",
      amount: 95,
      paymentMethod: "wallet",
      paidAt: "2026-06-18T13:35:00.000Z",
    },
    queue: {
      id: 502,
      queueNumber: 2,
      status: "completed",
    },
    referral: {
      id: 3001,
      reason: "Cardiology follow-up referral",
    },
    rating: {
      id: 701,
      score: 5,
      comment: "Very clear consultation.",
    },
  },
  {
    id: 1005,
    patientId: 4,
    doctorId: 3,
    clinicId: 3,
    referralId: null,
    type: "Initial Visit",
    priority: "2",
    status: "cancelled",
    requestedDate: "2026-06-24",
    startTime: "15:00:00",
    endTime: "15:30:00",
    actualStartTime: null,
    actualEndTime: null,
    reasonForVisit: "Neurology assessment.",
    symptoms: "Severe headache and dizziness.",
    cancellationReason: "Patient requested cancellation due to travel.",
    cancelledAt: "2026-06-23T17:20:00.000Z",
    checkinTime: null,
    notes: null,
    patient: {
      id: 4,
      user: {
        full_name: "Noah Carter",
        email: "noah.carter@example.com",
        phone: "+1 (555) 127-6654",
      },
    },
    doctor: {
      id: 3,
      user: {
        full_name: "Dr. Emily Davis",
        email: "emily.davis@clinic.com",
      },
    },
    clinic: {
      id: 3,
      name: "Lakeside Clinic",
      location: "Chicago",
    },
    payment: {
      status: "refunded",
      amount: 160,
      paymentMethod: "wallet",
    },
    queue: null,
    referral: null,
    rating: null,
  },
  {
    id: 1006,
    patientId: 5,
    doctorId: 4,
    clinicId: 4,
    referralId: null,
    type: "Return Visit",
    priority: "1",
    status: "no_show",
    requestedDate: "2026-06-20",
    startTime: "08:30:00",
    endTime: "09:00:00",
    actualStartTime: null,
    actualEndTime: null,
    reasonForVisit: "Sports injury follow-up.",
    symptoms: "Knee pain after training.",
    cancellationReason: null,
    cancelledAt: null,
    checkinTime: null,
    notes: "Marked no-show after missed appointment window.",
    patient: {
      id: 5,
      user: {
        full_name: "Ava Thompson",
        email: "ava.thompson@example.com",
        phone: "+1 (555) 338-9042",
      },
    },
    doctor: {
      id: 4,
      user: {
        full_name: "Dr. Michael Brown",
        email: "michael.brown@clinic.com",
      },
    },
    clinic: {
      id: 4,
      name: "Bayview Clinic",
      location: "San Francisco",
    },
    payment: {
      status: "forfeited",
      amount: 90,
      paymentMethod: "wallet",
    },
    queue: null,
    referral: null,
    rating: null,
  },
  {
    id: 1007,
    patientId: 3,
    doctorId: 5,
    clinicId: 5,
    referralId: null,
    type: "Initial Visit",
    priority: "1",
    status: "confirmed",
    requestedDate: "2026-07-15",
    startTime: "14:00:00",
    endTime: "14:30:00",
    actualStartTime: null,
    actualEndTime: null,
    reasonForVisit: "Skin irritation and allergy check.",
    symptoms: "Rash on arms.",
    cancellationReason: null,
    cancelledAt: null,
    checkinTime: null,
    notes: null,
    patient: {
      id: 3,
      user: {
        full_name: "Maya Brooks",
        email: "maya.brooks@example.com",
        phone: "+1 (555) 990-1134",
      },
    },
    doctor: {
      id: 5,
      user: {
        full_name: "Dr. Aisha Khan",
        email: "aisha.khan@clinic.com",
      },
    },
    clinic: {
      id: 5,
      name: "Greenfield Clinic",
      location: "Seattle",
    },
    payment: {
      status: "held",
      amount: 125,
      paymentMethod: "wallet",
    },
    queue: null,
    referral: null,
    rating: null,
  },
  {
    id: 1008,
    patientId: 2,
    doctorId: 2,
    clinicId: 5,
    referralId: null,
    type: "Return Visit",
    priority: "1",
    status: "completed",
    requestedDate: "2026-06-10",
    startTime: "09:30:00",
    endTime: "10:00:00",
    actualStartTime: "2026-06-10T09:34:00.000Z",
    actualEndTime: "2026-06-10T10:03:00.000Z",
    reasonForVisit: "Medication review.",
    symptoms: "Improving allergy symptoms.",
    cancellationReason: null,
    cancelledAt: null,
    checkinTime: "2026-06-10T09:15:00.000Z",
    notes: "Continue medication for one more week.",
    patient: {
      id: 2,
      user: {
        full_name: "Daniel Murphy",
        email: "daniel.murphy@example.com",
        phone: "+1 (555) 415-9821",
      },
    },
    doctor: {
      id: 2,
      user: {
        full_name: "Dr. Robert Chen",
        email: "robert.chen@clinic.com",
      },
    },
    clinic: {
      id: 5,
      name: "Greenfield Clinic",
      location: "Seattle",
    },
    payment: {
      status: "released",
      amount: 75,
      paymentMethod: "wallet",
    },
    queue: {
      id: 503,
      queueNumber: 1,
      status: "completed",
    },
    referral: null,
    rating: {
      id: 702,
      score: 4,
      comment: "Helpful follow-up.",
    },
  },
];
